<?php

namespace Rcalicdan\Ci4Larabridge\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

class EloquentCacheModels extends BaseCommand
{
    protected $group = 'Larabridge';
    protected $name = 'eloquent:cache_models';
    protected $description = 'Discovers and caches the list of Eloquent models for faster bootstrap.';

    public function run(array $params)
    {
        CLI::write('Starting Eloquent model caching process...', 'yellow');

        $cacheFile = $this->prepareCachePath();
        if ($cacheFile === null) {
            return 1;
        }

        $modelsArray = $this->findEloquentModels();
        $modelCount = count($modelsArray);
        CLI::write("Discovered {$modelCount} Eloquent model(s).", 'yellow');

        $phpContent = $this->generateCacheContent($modelsArray);

        if ($this->writeModelsToCache($cacheFile, $phpContent)) {
            CLI::write("Eloquent model list cached successfully to: {$cacheFile}", 'green');

            return 0;
        } else {
            CLI::error("Failed to write cache file: {$cacheFile}");

            return 1;
        }
    }

    private function prepareCachePath(): ?string
    {
        $cacheFile = WRITEPATH.'cache/eloquent_models.php';
        $cacheDir = dirname($cacheFile);

        if (! is_dir($cacheDir)) {
            CLI::write("Cache directory not found. Attempting to create: {$cacheDir}", 'cyan');
            if (! mkdir($cacheDir, 0755, true)) {
                CLI::error('Failed to create cache directory: '.$cacheDir);

                return null;
            }
            CLI::write("Cache directory created: {$cacheDir}", 'green');
        } elseif (! is_writable($cacheDir)) {
            CLI::error("Cache directory is not writable: {$cacheDir}");

            return null;
        }

        return $cacheFile;
    }

    private function findEloquentModels(): array
    {
        CLI::write('Discovering Eloquent models...', 'yellow');
        $models = [];
        $modelPath = APPPATH.'Models/';

        if (! is_dir($modelPath)) {
            CLI::write("Models directory not found: {$modelPath}", 'light_red');

            return [];
        }

        $files = glob("{$modelPath}*.php");
        if ($files === false || empty($files)) {
            CLI::write("No PHP files found in {$modelPath}", 'yellow');

            return [];
        }

        foreach ($files as $file) {
            $className = 'App\\Models\\'.basename($file, '.php');

            if (class_exists($className) && is_subclass_of($className, \Illuminate\Database\Eloquent\Model::class)) {
                $models[] = $className;
                CLI::write("Found: {$className}", 'green');
            } else {
                CLI::write("Skipped: {$className} (not a valid Eloquent model)", 'cyan');
            }
        }

        return $models;
    }

    private function generateCacheContent(array $modelsArray): string
    {
        $timestamp = date('Y-m-d H:i:s T');
        $exportedModels = var_export($modelsArray, true);

        return <<<PHP
<?php

// This file is automatically generated by the eloquent:cache_models command.
// Do not edit this file directly.
// Generated: {$timestamp}

return {$exportedModels};

PHP;
    }

    private function writeModelsToCache(string $filePath, string $phpContent): bool
    {
        if (file_put_contents($filePath, $phpContent) !== false) {
            return true;
        }

        return false;
    }
}
